"""Add city relationship to User model

Revision ID: 5fcc528fd78c
Revises: c8324a8fe93b
Create Date: 2024-07-01 12:53:03.793721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fcc528fd78c'
down_revision = 'c8324a8fe93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'city', ['city_id'], ['id'])
    op.drop_column('user', 'city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'city_id')
    # ### end Alembic commands ###
