"""initial migration

Revision ID: c8324a8fe93b
Revises: 
Create Date: 2024-07-01 12:28:41.665331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8324a8fe93b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('cost_of_electricity', sa.Float(), nullable=False),
    sa.Column('cost_of_fuel', sa.Float(), nullable=False),
    sa.Column('electricity_availability', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('user_type', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_user_id'), 'analytics', ['user_id'], unique=False)
    op.create_table('energy_benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('benchmark_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['city.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_benchmark_city_id'), 'energy_benchmark', ['city_id'], unique=False)
    op.create_table('energy_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_record_user_id'), 'energy_record', ['user_id'], unique=False)
    op.create_table('energy_saving',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('energy_record_id', sa.Integer(), nullable=False),
    sa.Column('saved_kwh', sa.Float(), nullable=False),
    sa.Column('money_saved', sa.Float(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['energy_record_id'], ['energy_record.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_energy_saving_energy_record_id'), 'energy_saving', ['energy_record_id'], unique=False)
    op.create_index(op.f('ix_energy_saving_user_id'), 'energy_saving', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_energy_saving_user_id'), table_name='energy_saving')
    op.drop_index(op.f('ix_energy_saving_energy_record_id'), table_name='energy_saving')
    op.drop_table('energy_saving')
    op.drop_index(op.f('ix_energy_record_user_id'), table_name='energy_record')
    op.drop_table('energy_record')
    op.drop_index(op.f('ix_energy_benchmark_city_id'), table_name='energy_benchmark')
    op.drop_table('energy_benchmark')
    op.drop_index(op.f('ix_analytics_user_id'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_table('user')
    op.drop_table('city')
    # ### end Alembic commands ###
