#!/usr/bin/env bash

# Update the package lists
sudo apt-get update

# Install Nginx
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx restart

