version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: energy_tracker_web
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=mysql+pymysql://root:password@db/energy_db
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: energy_tracker_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: energy_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: energy_tracker_frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app

volumes:
  mysql_data:

